let
    Fonte = Excel.Workbook(File.Contents("C:\"), null, true),
    SRA1 = Fonte{[Name="SRA"]}[Data],
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(SRA1, [PromoteAllScalars=true]),
    
    TipoAlterado = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {
        {"Cód.Diretoria", Int64.Type}, {"Diretoria", type text}, {"Cód.Área", Int64.Type}, {"Área", type text},
        {"Cód.SubArea", Int64.Type}, {"SubÁrea", type text}, {"Cód.Unidade", Int64.Type}, {"Unidade", type text},
        {"Matricula", Int64.Type}, {"Nome", type text}, {"Admissão", type date}, {"Demissão", type text},
        {"Motivo Demissão", type text}, {"Data de Nascimento", type date}, {"Código Estado Civil", Int64.Type},
        {"Estado Civil", type text}, {"Código Escolaridade", Int64.Type}, {"Escolaridade", type text},
        {"CPF", type text}, {"RG", type text}, {"Nome da mãe", type text}, {"Tipo Sexo", type text},
        {"Cód.Situação", Int64.Type}, {"Situação", type text}, {"Código Tipo Contrato", Int64.Type},
        {"Tipo Contrato", type text}, {"Salário", type number}, {"Cargo", Int64.Type}, {"Título Cargo", type text},
        {"Carreira", type text}, {"Hierarquia Cargo", type text}, {"CBO", Int64.Type}, {"Descrição CBO", type text},
        {"Marca Ponto", type text}, {"Cota Aprendiz", type text}, {"Código C.Custo", Int64.Type},
        {"Centro de Custo", type text}, {"Matrícula Gestor", Int64.Type}, {"Gestor", type text},
        {"Posto Gestor", Int64.Type}, {"Posto Gestor_1", type text}, {"Código Local", Int64.Type},
        {"Local", type text}, {"Código Filial", Int64.Type}, {"Nome Filial", type text}, {"CNPJ", type text},
        {"Posto", Int64.Type}, {"Descrição Posto", type text}, {"Descrição de atividades súmaria", type text},
        {"Insalubridade", Int64.Type}, {"Periculosidade", Int64.Type}, {"P.C.D", type text},
        {"Tipo de Deficiencia", type text}, {"Código Vínculo", Int64.Type}, {"Vínculo", type text},
        {"Código Sindicato", Int64.Type}, {"Descrição Sindicato", type text}, {"Escala", Int64.Type},
        {"Descrição Escala", type text}, {"Jornada Mensal", type number}, {"Data Última Alteração Posto", type date},
        {"Motivo Última Alteração Posto", type text}, {"Data Última Alteração Salarial", type date},
        {"Motivo Última Alteração Salarial", type text}, {"Data Última Alteração Cargo", type date},
        {"Motivo Última Alteração Cargo", type text}, {"Data Próxima Férias Programada", type text},
        {"Estrutura Salarial", Int64.Type}, {"Grade", Int64.Type}, {"Mínimo", Int64.Type}, {"Médio", Int64.Type},
        {"Máximo", Int64.Type}, {"Telefone 1", type text}, {"Telefone 2", type text}, {"E-mail Pessoal", type text},
        {"E-mail Corporativo", type text}, {"CEP", type text}, {"Rua", type text}, {"Bairro", type text},
        {"Cidade", type text}, {"UF", type text}, {"Número", type text}, {"Complemento", type text},
        {"Empresa", Int64.Type}, {"Razão", type text}
    }),
    SubstituicoesDiretoria = {
        {"0", "Dir. Exec. Pessoas, Sust.Resp.Social"},
        {"DIRETORIA EXECUTIVA ASSISTENCIAL E ENSINO", "Dir. Exec. Assistencial e Ensino"},
        {"DIRETORIA EXECUTIVA OPERACOES", "Dir. Exec. Operacoes"},
        {"DIRETORIA EXECUTIVA MEDICA, QUALIDADE E PESQUISA", "Dir. Exec. Medica, Qualidade e Pesquisa"},
        {"DIRETORIA EXECUTIVA FINANCAS, TI e SUPRIMENTOS", "Dir. Exec. Financas, TI e Suprimentos"},
        {"DIRETORIA EXECUTIVA PRESIDENCIA", "Dir. Exec. Presidencia"},
        {"DIRETORIA EXECUTIVA PESSOAS, SUSTENTABILIDADE E RESPONSABILIDADE SOCIAL", "Dir. Exec. Pessoas, Sust.Resp.Social"},
        {"DIRETORIA EXECUTIVA FINANCAS, TI, INFRA E SUPRIMENTOS", "Dir. Exec. Financas, TI e Suprimentos"},
        {"DIRETORIA EXECUTIVA FINANCAS, TI E SUPRIMENTOS", "Dir. Exec. Financas, TI e Suprimentos"},
        {"DIRETORIA EXECUTIVA SUSTENTABILIDADE E RESPONSABILIDADE SOCIAL", "Dir. Exec. Pessoas, Sust.Resp.Social"},
        {"DIRETORIA EXECUTIVA GENTE E GESTAO", "Dir. Exec. Pessoas, Sust.Resp.Social"},
        {"DIRETORIA EXECUTIVA EDUCACAO, PESQUISA, INOVACAO E SAUDE DIGITAL", "Dir. Exec. Medica, Qualidade e Pesquisa"},
        {"DIRETORIA EXECUTIVA MEDICA", "Dir. Exec. Medica"},
        {"DIRETORIA EXECUTIVA ASSISTENCIAL", "Dir. Exec. Assistencial e Ensino"},
        {"DIRETORIA EXECUTIVA NEGOCIOS, MARKETING E ESTRATEGIA", "Dir. Exec. Negocios, Marketing e Estrategia"},
        {"DIRETORIA SUPRIMENTOS", "Dir. Suprimentos"},
        {"DIRETORIA JURIDICA E COMPLIANCE", "Dir. Juridica e Compliance"}
    },
    SubstituicoesSindicato = {
        {"SINDICATO DOS EMPREGADOS EM ESTABELECIMENTOS DE SERVICOS DE SAUDE SAO PAULO", "Sind.Preponderante"},
        {"SINDICATO DOS FISIOTERAPEUTAS E TERAPEUTAS OCUPACIONAIS -  SAO PAULO", "Sind. Fisioterapeutas"},
        {"SINDICATO DOS MEDICOS DE SAO PAULO", "Sind. Médicos"},
        {"SINDICATO DOS ENFERMEIROS DE SAO PAULO", "Sind. Enfermeiros"},
        {"SINDICATO DOS TECNICOS E AUXILIARES EM RADIOLOGIA DE SAO PAULO", "Sind. Radiologistas"},
        {"SINDICATO DOS FARMACEUTICOS DE SAO PAULO", "Sind. Farmaceuticos"},
        {"SINDICATO DOS NUTRICIONISTAS DE SAO PAULO", "Sind. Nutricionista"},
        {"SINDICATO DOS TECNICO EM NUTRICAO DE SAO PAULO", "Sind. Téc. Nutricionista"},
        {"S.Tec.Seg.Trab.E.SP", "Sind. Tec. Segurança"},
        {"SINDICATO DE  PSICOLOGIA  DE SAO PAULO", "Sind. Psicologia"},
        {"ESTAGIARIOS", "Estagários"},
        {"APRENDIZES", "Aprendizes"},
        {"VOLKSWAGEM", "Sind. Volkswagem"},
        {"APRENDIZES - II", "Aprendizes"},
        {"SINDICATO DOS PROFESSORES DE SAO PAULO", "Sind. Professores"},
        {"SINDICATO DOS EMPREGADOS - PREPONDERANTE DE S.CTBA (SÃO JOSÉ DOS PINHAIS)", "Sind."},
        {"SINDICATO DOS EMPREGADOS - PREPONDERANTE ABC (SÃO BERNARDO)", "Sind."},
        {"SINDICATO DOS EMPREGADOS - PREPONDERANTE (TAUBATÉ)", "Sind."},
        {"Sind.Bibliotecários E.S.Paulo", "Sind."}
    },
    SubstituicoesUnidade = {
        {"CAMPO BELO", "Campo Belo"},
        {"CORPORATIVO", "Paulista"},
        {"CORPORATIVO - FINANÇAS, TI, INFRA E SUPRIMENTOS", "Paulista"},
        {"CORPORATIVO - GENTE & GESTÃO", "Paulista"},
        {"CORPORATIVO - INOVACAO E SAUDE DIGITAL", "Paulista"},
        {"CORPORATIVO - NEGÓCIOS, MARKETING E ESTRATÉGIA", "Paulista"},
        {"CORPORATIVO - OPERACOES", "Paulista"},
        {"CORPORATIVO - RESPONSABILIDADE SOCIAL", "Paulista"},
        {"DIGESTIVA", "Paulista"},
        {"GSP", "Paulista"},
        {"HOSPITAL VERGUEIRO", "Vergueiro"},
        {"IPE", "Paulista"},
        {"MATRICIAL - ASSISTENCIAL", "Paulista"},
        {"MATRICIAL - MÉDICO", "Paulista"},
        {"ONCOLOGIA", "Paulista"},
        {"PAULISTA", "Paulista"},
        {"RESP. SOCIAL", "Resp. Social"}
    },

    SubstituicoesSituacao = {
        {"0", "Pensao"},
        {"Acidente Trabalho", "Lic.Medica"},
        {"APOSENTADOS INVALIDEZ", "Aposentado"},
        {"Auxilio Doenca", "Lic.Medica"},
        {"Contrato Suspenso", "Contrato Suspenso"},
        {"Demitido", "Demitido"},
        {"Ferias", "Trabalhando"},
        {"Lic.Medica Dias/Hrs.", "Lic.Medica"},
        {"Licença Maternidade", "Lic.Medica"},
        {"Licença Maternidade Estendida", "Lic.Medica"},
        {"Trabalhando", "Trabalhando"}
    },
    AplicaDiretorias = List.Accumulate(SubstituicoesDiretoria, TipoAlterado, (estado, par) =>
        Table.ReplaceValue(estado, par{0}, par{1}, Replacer.ReplaceText, {"Diretoria"})
    ),
    AplicaSindicatos = List.Accumulate(SubstituicoesSindicato, AplicaDiretorias, (estado, par) =>
        Table.ReplaceValue(estado, par{0}, par{1}, Replacer.ReplaceText, {"Descrição Sindicato"})
    ),
    AplicaUnidade = List.Accumulate(SubstituicoesUnidade, AplicaSindicatos, (estado, par) =>
        Table.ReplaceValue(estado, par{0}, par{1}, Replacer.ReplaceValue, {"Unidade"})
    ),
    AplicaSituacao = List.Accumulate(SubstituicoesSituacao, AplicaUnidade, (estado, par) =>
        Table.ReplaceValue(estado, par{0}, par{1}, Replacer.ReplaceText, {"Situação"})
    )
in
    AplicaSituacao
